"""Manually recreate appointment_status enum

Revision ID: 39e64ff40b78
Revises: 
Create Date: 2025-07-21 20:51:47.233431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e64ff40b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE appointment_status RENAME TO appointment_status_old")
    op.execute("CREATE TYPE appointment_status AS ENUM('scheduled', 'completed', 'cancelled')")
    op.execute(
        "ALTER TABLE appointment ALTER COLUMN status TYPE appointment_status USING status::text::appointment_status"
    )
    op.execute("DROP TYPE appointment_status_old")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE appointment_status_old AS ENUM('SCHEDULED', 'COMPLETED', 'CANCELLED')") # Assuming old values were uppercase
    op.execute(
        "ALTER TABLE appointment ALTER COLUMN status TYPE appointment_status_old USING status::text::appointment_status_old"
    )
    op.execute("DROP TYPE appointment_status")
    op.execute("ALTER TYPE appointment_status_old RENAME TO appointment_status")
    # ### end Alembic commands ###
