"""Refactor models and add indexes

Revision ID: ca4f0f1d115c
Revises: 39e64ff40b78
Create Date: 2025-07-21 21:13:13.206296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4f0f1d115c'
down_revision = '39e64ff40b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=True))

    # Set a default value for existing rows
    op.execute("UPDATE payment SET payment_type = 'income' WHERE payment_type IS NULL")

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('payment_type', nullable=False)
        batch_op.create_index(batch_op.f('ix_payment_patient_id'), ['patient_id'], unique=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_payment_patient_id'))
        batch_op.drop_column('payment_type')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_date'))

    # ### end Alembic commands ###
