"""Remove payment_method from Payment model

Revision ID: d033dda8c130
Revises: be967d7ed86d
Create Date: 2025-04-24 13:06:02.681466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd033dda8c130'
down_revision = 'be967d7ed86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
